<?php

/**
 * @file
 * Contains bhcc_contact_triage module file.
 */

/* use Drupal\node\NodeInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\bhcc_localgov_directories\DirectoriesExtraFieldDisplay; */
use Drupal\pathauto\Entity\PathautoPattern;
use Drupal\Core\Entity\ContentEntityInterface;


/**
 * Implements hook_pathauto_pattern_alter().
 */
function bhcc_contact_triage_pathauto_pattern_alter(PathautoPattern $pattern, array $context) {

  // Is it contact_triage_form content type ?
  // if so strip out contact-council/ from the path
  $entity = reset($context['data']);
  assert($entity instanceof ContentEntityInterface);
  if ($entity->bundle() === 'contact_triage_form' && $entity->hasField('localgov_services_parent') && $entity->localgov_services_parent->target_id && strpos($pattern->getPattern(), '[node:localgov_services_parent:entity:url:relative]') === FALSE) {

    // @todo add comments here
    $root_pattern = $pattern->getPattern();

    $root_pattern = str_replace('contact-council/', '', $root_pattern);

    $pattern->setPattern('[node:localgov_services_parent:entity:url:relative]/' . $root_pattern);
  }
}