<?php

/**
 * @file
 * Contains bhcc_contact_triage module file.
 */

use Drupal\pathauto\Entity\PathautoPattern;
use Drupal\Core\Entity\ContentEntityInterface;


/**
 * Implements hook_pathauto_pattern_alter().
 */
function bhcc_contact_triage_pathauto_pattern_alter(PathautoPattern $pattern, array $context) {

  // Is it contact_triage_form content type ?
  // if so strip out contact-council/ from the path
  $entity = reset($context['data']);
  assert($entity instanceof ContentEntityInterface);
  // if a contact triage form get the url and remove the 1st occurence of 'contact-council/'
  if ($entity->bundle() === 'contact_triage_form' && $entity->hasField('localgov_services_parent') && $entity->localgov_services_parent->target_id && strpos($pattern->getPattern(), '[node:localgov_services_parent:entity:url:relative]') === FALSE) {

    $root_pattern = $pattern->getPattern();
    if (strpos($root_pattern, 'contact-council/') !== 0 ) {
      $left = substr($root_pattern, 0, strpos($path, 'contact-council/'));
      $right = substr($root_pattern, (strpos($path, 'contact-council/') + 16));
      $root_pattern = $left . $right;
    }

    $pattern->setPattern('[node:localgov_services_parent:entity:url:relative]/' . $root_pattern);
  }
}